const story = "<p>" +
"What, exactly, is it that scares us in the night ? What is it that so totally envelops a person in shadowy darkness, reaching through the darkest corners of the mind, and pulls out monstrosities so real, so incredibly detailed and hideous ? Is it our imagination, or is it perhaps a shred of a memory, long forgotten in the recesses of the human brain ? Do we all have a basic distrust of the darkness ? What is it that is hiding, right at this very moment, even mere feet away from you, as you squeeze your eyes shut, pulling the covers tighter to your chin, and tucking your feet carefully underneath the blanket, so as not to be exposed to some terribly clawed, foul demon.What could possibly be lurking outside, behind the old rusty shed, in the blanketed darkness that can’t be illuminated by the low watt light bulb on your porch, while you quickly and silently huff down a good old cigarette, the last before a fit of troubled dreams ? Its eyes a sickly yellow, perhaps its teeth sharp as a razor, one eye dark and bloodshot, the other missing, as with the rest of the skin on its face, claws rapping softly against the shed as a tree branch would do, lulling you into a false sense of security right before making its killer debut ? " +
+ "<br>" +
"Or maybe it’s hanging above the awning, a great winged creature with a sharp face, long, thin nose, and fangs that dripped black sludgy blood, coagulated on its tongue, onto your shoulder as you stand beneath? Perhaps the rustling of the leaves is more than just a rustle. Perhaps its actually a serial murderer, perhaps dressed as a clown, ready to cleave you into two separate halves before ripping through your home, decimating anything, and, more importantly, anyone in their sight? Or maybe the sound of something rolling in the halls, while you squint your blinded eyes, vaguely seeing the strange outline of something rather mundane, is actually a creature unfolding itself and propelling itself quite quickly down the hall to make quick work of you and your entire family?"
+ "<br>" +
"As a seeing impaired person, Melinda felt a connection with the last statement. There had been many times, some quite recently, when her vision had played tricks on her, but lately it was all the time. What she saw in the dark, she saw also in the light, and suddenly she was quite sure she needed to focus, to continue writing her particular set of ‘fiction’, that is, false on the outside, but right on the inside of her mind, it was all quite true. Fantastical monsters, perhaps not as cut and dry as your run of the mill vampires and werewolves, had been a daily sighting for her. She had the gift of imagination, her mother had told her dryly, one afternoon where she had run outside of their home in tears and into her mothers lap, to the surprise of the rest of the guests at her parent’s small anniversary party. The children had been in bed hours ago, the clock rapidly reaching midnight, when Melinda had awoken to the feeling of being watched quite intensely by the darkest shadow she had ever seen, poised readily in the corner, next to her run down vanity and the coat-hook so misplaced but without another home. She had believed, as a child whose vision was steadily worsening, that it had one large glowing red eye, its head rather bumpy looking, with a thick neck but slender body, with long arms and an almost comically short bottom."
+ "<br>" +
"Her mother and apologized to the few people who remained so late, her smile quick and genuine as she scooped little Melinda into her arms and carried her carefully up the thirteen stairs to the second floor. Melinda focused her attention on the warmth and love that radiated from her mother, the one thing her preadolescent mind knew to be one hundred percent real. Her mother hummed a little tune under her breath, one that made Melinda feel safe, and when she arrived back to her bedroom, she was hardly afraid anymore. Until they walked in and she glimpsed the monster in the corner."
+ "<br>" +
"Melinda let out a scream of terror, grappling for a better hold on her mother, who, taken completely by surprise, had almost toppled over with her. Marie let out a gasp, gazing fleetingly at the being in the corner, before flickering the light on. Both of them stared at the coat hook, where a top hat was turned sideways with a single gem winking brightly red. The coat that was hung beneath it was spread quite far, almost like it had been deliberately placed there. Underneath was a squat little vanity stool, very prim, which was the added short bottom to the great monster of the corner."
+ "<br>" +
"Marie, Melinda’s dear mother, started to laugh to the point of hysteria, and Melinda had joined, her small, pure voice holding a tinge of confusion, but otherwise unaware of the shared fear that had transpired. It wasn’t until much later, when her mother’s journals had been found, that Melinda had had any inkling of the great terror her mother felt for the dark. And how much of it was utterly true for her as well."
+ "<br>" +
"For years, up to her mother’s passing just a year prior, she had grown up to understand that some things were just the way they were. When she saw the ugly faces underneath the masks of otherwise polite people, she understood that it was almost a sort of glamour that people had. They would put on the mask and pretend to care, before going home and harping about just how terrible everything, and everyone, was. They would pretend to empathize while mentally planning out their time off, simply nodding or shaking their head, with the proper awws and oh nos thrown in here and there."
+ "<br>" +
"She also understood that people were their truest self in the dark. While she herself was quite terrified of whatever nightly creature would crawl, bones bopping and flesh hanging loosely, dark, oozing blood and pus leaking all over her carpet, its mouth open and salivating for a taste of her flesh, she knew that some people would thrive on being the monster in her head. Feeding on her fear, breathing in the acrid smell of her sweat and she perspired profusely from terror. She knew that those monsters were quite real, and thrived on darkness."
+ "<br>" +
"What she hadn’t known until her mother died was that some of those people, the ones who seemed to thrive on inflicting pain and misery on others, weren’t doing it entirely of their own accord. Some of them, she found out, had seemed to attract an ethereal being, a shadow that fed on them until it took its fill, then proceeded to leave its victim an empty shell, no emotions, no feelings of attachment to humanity. Just a shell of a human without a mind to process that it was already dead. It breathed, it smiled, it feigned emotion. But the eyes were dead. And soon after, the body would begin to rot. The organs continued to work, the brain fired and sent little messages to the body, but the overall essence that was there was now gone, digested by a shadow that only grew larger the longer it was able to feed."
+ "<br>" +
"So, their soul, or whatever remnants were left, rotted away. Once the body was left, stripped from its soul, it began to shut down. It would deteriorate in full, until a strange heart attack, or sudden violent outburst which left the body dead, would occur. All of this was found in her mother’s journals, which she kept quite neat and succinct, as opposed to her other fictional works, which ebbed and flowed, had twists and turns, and took a reader on quite the ride to just pass along the simplest of messages. It also kept a very detailed record of not only all the occurrences she herself had experienced, but also those of her only daughter. Melinda. She was afraid that the shadows, which could take the form of any creature, both real and imagined, would take her only child, effectively destroying two people at once."
+ "<br>" +
"Melinda quickly typed another paragraph, ignoring the cold tendrils of fear that curled against the back of her neck, the small, fine hairs that grew there standing up, goose flesh popping all over her skin. She suppressed a shudder, her breath hitching as the room seemed to drop another five degrees, the dim, flickering light of her last bulb washing her and her laptop in an eerie yellowish light. The shadows that stirred in the corners seemed to mock her, leering at her from the corner of her eyes, where she was unable to focus her vision. She thought she saw a jacket move on the hook next to the front door, but of course it could have been her imagination. She funneled her attention back into the comforting click clack of the keys, but before she could continue on this last paragraph, a sound reached her ears, honed from the misfortune of having become legally blind. The only blessing she had ever received was her spectacular hearing, and right now she could hear the soft footfalls of someone walking through the snow towards her front door."
+ "<br>" +
"With a renewed sense of urgency, she shook off the trepidation and allowed her fingers to fly over the keys, pausing occasionally to backtrack. Her mother had passed, and while that in itself was a shock, due to her advanced age of only forty-three, it was more the method on which she had passed that had first created the total dread Melinda now felt. She had died, quite literally, of fright. Her heart and stopped, so the officially ruling would be a heart attack, but the utter look of terror on her face, the way her mouth had twisted into a silent scream, her eyes wide and frozen, had told her that each and every entry in her journals had been true. Or at least true enough to become reality."
+ "<br>" +
"Melinda quickly finished, hurriedly sending the link, just as the piece of technology crashed. The screen went blank; no, it went dark. There was no hint of light in the background indicating it had just closed out and was waiting to restart. This was the utter deadness, and just as the bang of a monstrous hand resounded against her oak door, the light bulb blew, leaving the room in total darkness."
+ "<br>" +
"She threw herself back, scrambling to find the flashlight she kept close to her at all times, and only succeeded in knocking her head against the desk corner. Dazed and more than a little confused, she squinted at the figures that swam before her, long and quite symmetrical. She realized with a start that she could smell blood, and could hear the faint whisper of their shadowy selves moving forward, reaching out to grasp her and pull her to them to commit some strange atrocity, or perhaps just to suck the fear out of her until she was no more than a husk, empty and dull."
+ "<br>" +
"She screamed, the sound guttural and raw, as she pushed herself back and scrambled for purchase on the thirteen stairs that lead to the second floor, where her bathroom was. She had planned to face her darkness, to try to defeat it, to maybe control it in a way, but it was with no little surprise that she realized it would not be possible. Her hand left a slick trail on the banister as she stumbled up the stairs, tripping on the second to last stair. She felt claws close around her ankle, biting in, a snicker and growl from behind her, before yanking herself up. The creature let go, almost as if it hadn’t thought she would attempt an escape, and for a moment Melinda thought she felt an understanding. Before she could dwell on that, the loud pounding at the door sent her to the bathroom, where she flicked on the fluorescent lights that blazed across her sweat slicked skin, over the thin coating of blood that dripped steadily down her left eye. She swiped her hand across it, belatedly realizing that this may have been the blood she had smelled. She closed her eyes, chest heaving, as the monster outside banged against the door hard enough to knock it inwards, crashing into the glass case that had belonged to her Marie. She heard the shatter, and the thud of steps. She looked up blearily as the door to the bathroom was yanked open and she was dragged out by great blobs of black, obscuring the bright light but not dissipating as she had originally thought they would."
+ "<br>" +
"She frowned, the effort great as she felt a heavy weakness overtake her body. Her eyelids drooped, and through slitted eyes she thought she could see pale faces etched in shock. Her frown deepened momentarily before she slid blissfully into a dreamless sleep from which she would wake and remember very little."
+ "<br>" +
"What Melinda did not know, and would probably never know, was that she suffered from an illness, one that turned benign beings into monsters, that whispered great untruths into her ear daily, causing hallucinations that felt so real that she acted upon them. What she thought to have been her mother’s death due to shadows, had actually been the murder of Marie by Melinda herself. Melinda was the shadow, had perhaps made a plausible reason for her descent into madness to make herself feel less ashamed, less aware of the slow rot of her own brain that had wedged her solely into insanity."
+ "<br>" +
"The last thing Melinda ever saw, later, was the greatest ending to the story she had started so long ago, always on the edges of her brain, obscured by the amnesia that had quickly set in the following days after she had been detained for the murder of Marie Henderson and, later on, the murder of Derek Henderson, the brother Melinda’s mind effectively washed away as if he had never existed. As the needle edged closer to her skin, she could see the wink of a red eye, and she was dimly aware of the being unfolding itself, its top half quite hefty, moved along by a bottom that was quite funny. As the needle pressed in, a cool numbness enveloped her as the shadow with the winking eye enveloped her in its arms. She smiled then, the small smile of a child, as she felt, for the first time in years, quite safe and loved. Forever embraced by the darkness from which she would never know what lurked beyond."
+ "<br>" +
"Credit : Tatyana Tieken"
+ "<br>" +
"Website: <a href=\"https://www.creepypasta.com/what-lurks-in-shadows/\">https://www.creepypasta.com/what-lurks-in-shadows/</a>"
+ "</p>"

module.exports = story;
